source 'https://rubygems.org'
ruby '1.9.3'
gem 'rails', '3.2.17'

gem "dragonfly", "~> 1.0.2"
gem 'dragonfly-s3_data_store'

gem 'rack-cache', require: 'rack-cache'
# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

group :development do
  gem 'sqlite3'
end

group :production do
  gem 'pg'
  gem 'memcachier'
  gem 'dalli'
end

group :test do
  gem 'cucumber-rails', :require => false
  gem 'database_cleaner'
  gem "rspec-rails", "~> 2.14.1"
  gem 'selenium-webdriver'
  gem 'factory_girl_rails'
  gem 'rack_session_access', git: 'https://github.com/railsware/rack_session_access.git'
end


gem 'thin'

gem "omniauth-twitter"

gem 'annotate'

gem 'cancan'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby
  gem 'haml-rails', '~> 0.3.5'
  gem 'uglifier', '>= 1.0.3'
  gem 'bootstrap-sass', '2.3.2.2'
  gem "bootstrap-will_paginate", '0.0.9'
  gem "compass-rails", "~> 1.1.2"
  gem 'compass', '>= 0.12.5'
  gem "jscrollpane-rails"
  gem "jquery-mousewheel-rails"
  gem 'mwheelintent-rails'

  gem 'statistics2'
end

gem 'jquery-rails'
gem 'jquery-ui-rails'
gem "will_paginate"
# gem "kaminari"

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
